execute pathogen#infect()
filetype plugin indent on

syntax enable

colorscheme monokai
" Make background terminal background
hi Normal ctermbg=none
" Make unwritten portion background terminal background
highlight NonText ctermbg=none
" Make line number background terminal background
highlight LineNr ctermfg=grey ctermbg=none

set filetype=dosini
set number
set showmatch
set hlsearch
set laststatus=2
set guifont=Hack13
set noshowmode
au BufReadPost *.swipl set syntax=prolog

let g:lightline = {
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'fugitive', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'fugitive': 'LightlineFugitive',
      \   'readonly': 'LightlineReadonly',
      \   'modified': 'LightlineModified',
      \   'filename': 'LightlineFilename'
      \ },
      \ 'separator': { 'left': "\uE0B0", 'right': "\uE0B2" },
      \ 'subseparator': { 'left': "\uE0B1", 'right': "\uE0B3" }
      \ }

" + icon indicates file was modified
function! LightlineModified()
	if &filetype == "help"
		return ""
	elseif &modified
		return "+"
	elseif &modifiable
		return ""
   	else
		return ""
	endif
endfunction

" Add lock icon to read-only file names
function! LightlineReadonly()
	if &filetype == "help"
		return ""
	elseif &readonly
		return ""
	else
		return ""
	endif
endfunction

" Add branch icon to fugitive branch
function! LightlineFugitive()
	if exists('*fugitive#head')
		let branch = fugitive#head()
		return branch !=# '' ? ' '.branch : ''
	endif
	return ''
endfunction

if !has('gui_running')
	  set t_Co=256
endif
